/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.newproject;

import javax.swing.JFrame;

/**
 *
 * @author Diya Seshan
 */
public class SupplierHomePage extends javax.swing.JFrame {
    
    String SupplierID = "";
    /**
     * Creates new form SupplierHomePage
     */
    public SupplierHomePage() 
    {
        initComponents();
        this.setTitle("Supplier Home");
         // Center the window on the screen
        this.setLocationRelativeTo(null);
        // Set default close operation
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        this.setResizable(false);
    }
    public SupplierHomePage(String UserID) 
    {
        this.SupplierID = UserID;
        initComponents();
        this.setTitle("Supplier Home");
         // Center the window on the screen
        this.setLocationRelativeTo(null);
        // Set default close operation
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        this.setResizable(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manage_pending_orders = new javax.swing.JButton();
        track_past_orders = new javax.swing.JButton();
        manage_inventory = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Supplier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manage_pending_orders.setText("Manage Pending Orders");
        manage_pending_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_pending_ordersActionPerformed(evt);
            }
        });

        track_past_orders.setText("Track Past Orders");
        track_past_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                track_past_ordersActionPerformed(evt);
            }
        });

        manage_inventory.setText("Manage Inventory");
        manage_inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_inventoryActionPerformed(evt);
            }
        });

        back.setText("Logout");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        Supplier.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Supplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Supplier.setText("Supplier Home Page");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manage_pending_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(track_past_orders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manage_inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(back)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Supplier)
                .addGap(44, 44, 44)
                .addComponent(manage_pending_orders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(track_past_orders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manage_inventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        // go back to HOME PAGE
        LoginPage lp = new LoginPage();
        lp.show();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void manage_pending_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_pending_ordersActionPerformed
        // TODO add your handling code here:
        SupplierPendingOrders sp = new SupplierPendingOrders(this.SupplierID);
        sp.show();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_manage_pending_ordersActionPerformed

    private void track_past_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_track_past_ordersActionPerformed
        // TODO add your handling code here:
        SupplierTrackPastOrders st = new SupplierTrackPastOrders(this.SupplierID);
        st.show();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_track_past_ordersActionPerformed

    private void manage_inventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_inventoryActionPerformed
        // TODO add your handling code here:
        ManageInventory mi = new ManageInventory(this.SupplierID);
        mi.show();
        this.setVisible(false);
        this.dispose();        
    }//GEN-LAST:event_manage_inventoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Supplier;
    private javax.swing.JButton back;
    private javax.swing.JButton manage_inventory;
    private javax.swing.JButton manage_pending_orders;
    private javax.swing.JButton track_past_orders;
    // End of variables declaration//GEN-END:variables
}
